services:
  db:
    container_name: SwitfAPI-db
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    container_name: SwiftAPI
    build:
      context: SwiftAPI/
      dockerfile: Dockerfile.dev
    volumes:
      - ./SwiftAPI:/app
      - node_modules:/app/node_modules

  nginx:
    container_name: SwiftAPI-nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres-data:
  node_modules:
